Magento headless integration demo with Vuejs - V1
adyen-examples/magento-headless-demo pull request #6
Opened 2023-06-19 09:01 UTC by ayodejidev

2023-06-20 13:09 UTC, hossam-adyen approved these changes

2023-06-20 13:09 UTC, hossam-adyen commented on magento-backend/README.md
> +4. Open a new Terminal in the current directory and run `./install.sh` to install and configure the Adyen payment plugin.
you might consider do the installation step via a service in your [docker-compose.yml]

```
  install:
    image: ataberkylmz/magento2:2.4.4
    container_name: magento2-container
    .
    .
    .
    entrypoint:   install.sh
```

2023-06-20 13:09 UTC, hossam-adyen commented on magento-backend/README.md
> +## Running online with [Gitpod](https://gitpod.io/)
can we have the steps to run locally?

2023-06-20 13:15 UTC, ayodejidev commented on magento-backend/README.md
> +4. Open a new Terminal in the current directory and run `./install.sh` to install and configure the Adyen payment plugin.
Thank you! Will definitely look into this.

2023-06-20 13:16 UTC, ayodejidev commented on magento-backend/README.md
> +## Running online with [Gitpod](https://gitpod.io/)
Yes. We are working on it. Will be updated soon.

2023-06-27 16:24 UTC, Kwok-he-Chu requested changes
Nice work on this! I just added my feedback for the extra mile to go from `90%` to `120%` in terms of Developer Experience ;) I ran into some issues making it work, but I hope that my suggested changes will benefit the developers, especially those who have never worked with gitpod nor did any configuration from the start.

2023-06-27 16:24 UTC, Kwok-he-Chu commented on README.md
> +2. Launch the frontend (VueJs Sample)[https://github.com/adyen-examples/magento-headless-demo/tree/develop/vue-frontend] and backend (Magento instance)[https://github.com/adyen-examples/magento-headl
The links here are not properly displayed `(swap the brackets)` -> `[ ]`
- [x] `[VueJs Sample](vue-frontend)`
- [x] `[Magento backend instance](magento-backend)`

2023-06-27 16:24 UTC, Kwok-he-Chu commented on .gitpod.yml
> +              echo "I AM HERE"
Remove "I AM HERE" or change it to some other 'useful' message that writes to the console :)

2023-06-27 16:24 UTC, Kwok-he-Chu commented on README.md
> +1. Add your API Keys to your Gitpod variables
Specify which the necessary `API Keys` with the respective names

2023-06-27 16:24 UTC, Kwok-he-Chu commented on .gitpod.yml
> +            if [ -z ${BASE_URL+x} ] || [[ -z ${BEARER_TOKEN+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]]; then
Flow:
I did not set the initial BASE_URL, BEARER_TOKEN values. This results into the vue-frontend not being started (which is confusing for developers). We'll have to update the readme accordingly so that it's clear what values go into this line.

2023-06-27 16:24 UTC, Kwok-he-Chu commented on README.md
> +- Configure Magento API endpoint:
Looking at this, we need to start the vue-frontend, then update the variables BaseUrl and BearerToken (which we do not have initially).

My recommendation would be the following:
1) Move the frontend setup wards in the readme.
2) Provide the developer step-by-step instructions to configure the headless integration (including which application to start first and what values to-set on the way

2023-06-27 16:24 UTC, Kwok-he-Chu commented on README.md
> +   Open the `vue-frontend/pages/preview.vue` file and update the `baseURL` variable with your Magento Instance URL endpoint and `bearerToken` with the integration token created in Magento.
Name `BASE_URL` in gitpod-file, `BEARER_TOKEN` in gitpod-file consistenly (to avoid confusion)

I assume that we need to update our frontend (vue-frontend) so that it points to the baseUrl of our magento backend. For this-to-work, we also need to restart our vue-frontend with the new config. Include these steps

2023-06-27 16:24 UTC, Kwok-he-Chu commented on README.md
> +- Gitpod account (if you want to use Gitpod as the development environment)
Gitpod account supports Google OAuths, a gitpod account is not necessarily required. You can just say: "access to gitpod" Google/sign-ins can also be option

2023-06-27 16:24 UTC, Kwok-he-Chu commented on vue-frontend/README.md
> +[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/carlosperales95/magento-headless-demo/tree/develop/vue-frontend)
The URL points at a repository outside of adyen-examples, we should update this using a relative link (not the develop branch)

2023-06-27 16:24 UTC, Kwok-he-Chu commented on vue-frontend/README.md
> +# Adyen [online payment](https://docs.adyen.com/checkout) integration demos
Consider merging readmes here (on magento backend, vue-frontend) by Updating the README to suit the gitpod use-case. Explain them how they can use it. 

Because this demo has two folders that need to work in unison, perhaps consider one giant README in the /root directory instead of our current 3 READMEs that may provide information to developers who are trying to start the application.

2023-06-27 16:24 UTC, Kwok-he-Chu commented on vue-frontend/.github/workflows/e2e.yml
> +        run: docker run --rm -d --name test-image -p 8080:8080 -e PORT=8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CL
[Out-of-scope] I would remove these E2E tests and write a different one, if you create a ticket, I can help you write them.

Consider: Running a different E2E testing-suite here, one that spins-up the magento-backend, one that spins-up the vue-frontend, followed by making the test payment through the vue-frontend.

2023-06-27 16:24 UTC, Kwok-he-Chu commented on magento-backend/.gitpod.yml
> +tasks:
I don't think this gitpod file is used unless you start it from the /root directory ?

2023-06-27 16:24 UTC, Kwok-he-Chu commented on magento-backend/.gitpod.yml
> +tasks:
We can remove it (I think*) as we already have a .gitpod.yml file in the root

2023-06-30 03:34 UTC, ayodejidev commented on .gitpod.yml
> +              echo "I AM HERE"
Fixed. Thanks for your feedback.

2023-06-30 03:35 UTC, ayodejidev commented on .gitpod.yml
> +            if [ -z ${BASE_URL+x} ] || [[ -z ${BEARER_TOKEN+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]]; then
This step has now been improved in the updated README.

2023-07-03 07:32 UTC, gcatanese reviewed
Anything to do or remark about webhooks?

2023-07-03 07:32 UTC, gcatanese commented on README.md
> +- Github account (if you want to use Gitpod as your development environment)
You are asking "if you want to use Gitpod as your development environment" but this repo only explains how to run it on Gitpod, I would remove the text then

2023-07-03 07:32 UTC, gcatanese commented on README.md
> +- Prior knowledge of how to spin up the [Vue Online Payment Demo](https://github.com/adyen-examples/adyen-vue-online-payments)
Do users need prior knowledge of the Vue Sample app? Maybe experience with the language

2023-07-03 07:32 UTC, gcatanese commented on README.md
> +3. Launch the backend [Magento instance](https://github.com/adyen-examples/magento-headless-demo/tree/develop/magento-backend)
The link to launch the backend should the first bullet point in the Backend Setup (like in the Frontend setup)

2023-07-03 07:32 UTC, gcatanese commented on README.md
> +5. Update  `BEARER_TOKEN` variable created in [Gitpod](https://gitpod.io/variables) with the copied token and save.
Is saving the value enough? Will the workspace pick up the new value while running?

2023-07-04 16:49 UTC, Kwok-he-Chu commented on README.md
> +5. Update  `BEARER_TOKEN` variable created in [Gitpod](https://gitpod.io/variables) with the copied token and save.
I've revamped the readme with the appropiate steps. The `Bearer_Token` is created from the backend (configuration/magento). After those steps, you need to spin-up the frontend (which will have the updated `BEARER_TOKEN`) on startup

2023-07-04 16:49 UTC, Kwok-he-Chu approved these changes

2023-07-04 16:50 UTC, merged